initial commit приложения Filmorate
Sweta304/java-filmorate pull request #1
Opened 2022-06-05 22:15 UTC by Sweta304

2022-06-06 16:15 UTC, alexache requested changes
Оставил комментарии по коду

2022-06-06 16:15 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.contains(film)) {
(можно лучше) В List<Film> films есть определенные недостатки - для поиска наличия фильма приходится обходить весь список, так же и для обновления фильма. Будет лучше хранить в виде маппинга - id -> объект (то есть в хэш мапе), как в прошлых спринтах. Тогда поиск и обновление будет работать заметно быстрее

2022-06-06 16:15 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilms() {
Действительно ли нужен отдельный метод, почему нельзя воспользоваться в тесте getAllFilms() ?

2022-06-06 16:15 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
(можно лучше) я бы предложил разделить User / Film в разные тест классы, у него ведь нет никакого общего функционала, по крайне мере сейчас

2022-06-06 16:15 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        assertTrue(userController.getUsers().isEmpty(),"добавлен пользователь с некорректным email");
А почему сделано через assertTrue, а не assertThrows(), как выше? Разве заранее не известно, какой из эксепшенов тут возможен?

2022-06-06 16:15 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +//    @Test
Закомментированный код лучше удалять

2022-06-06 16:15 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    void IncorrectFilmReleaseDate() {
Имена методов не стоит начинать с заглавной буквы

2022-06-06 16:15 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +//    @Test
Закомментированный код лучше удалять

2022-06-06 16:15 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@ConfigurationProperties(prefix="application.properties")
А для чего здесь эта аннотация?

2022-06-06 20:10 UTC, Sweta304 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        assertTrue(userController.getUsers().isEmpty(),"добавлен пользователь с некорректным email");
Сделала так, чтобы проверить работу аннотации @Email, или наверное это вообще лишнее? Еще почему то не работает валидация на некорректный e-mail - при наличии аннотации @Email, все равно без ошибок создается юзер с указанной почтой вида "box@"

2022-06-06 20:15 UTC, Sweta304 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    void IncorrectFilmReleaseDate() {
исправлено

2022-06-06 20:16 UTC, Sweta304 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@ConfigurationProperties(prefix="application.properties")
удалила, пробовала экспериментировать, т.к. не работала валидация e-mail

2022-06-07 20:06 UTC, Sweta304 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.contains(film)) {
исправлено

2022-06-07 20:07 UTC, Sweta304 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilms() {
убрала, действительно лишний

2022-06-07 20:07 UTC, Sweta304 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
готово

2022-06-07 20:07 UTC, Sweta304 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +//    @Test
убрала

2022-06-07 20:07 UTC, Sweta304 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    void IncorrectFilmReleaseDate() {
исправлено

2022-06-07 20:08 UTC, Sweta304 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +//    @Test
удалила

2022-06-08 20:52 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (films.containsValue(film)) {
(можно лучше) все равно это выглядит немного странным, проход по всей мапе тоже будет накладной операцией, в ТЗ не было про проверку уникальности фильма, поэтому пока можно было пренебречь наверное

2022-06-08 20:58 UTC, alexache approved these changes
Теперь все выглядит ок

2022-06-19 07:09 UTC, merged